export default {
    SET_CONTENT: 'SET_CONTENT',
    SET_DAYS: 'SET_DAYS',
    SET_EVENTS: 'SET_EVENTS',
    SET_TYPES: 'SET_TYPES',
    SET_LOCATIONS: 'SET_LOCATIONS',
    CONTENT_LOADED: 'CONTENT_LOADED',
    TOGGLE_PLAY: 'TOGGLE_PLAY',
    SET_SIZES: 'SET_SIZES',
    SET_CALENDAR: 'SET_CALENDAR',
    SET_BASE: 'SET_BASE',
    SET_FILTERS: 'SET_FILTERS',
    RESET_FILTERS: 'RESET_FILTERS'
}